networks:
  walletnet:
    driver: bridge
    external: true

services:
  app:
    build: .
    image: spring-wallet:latest
    container_name: consumer-app
    restart: on-failure
    tty: true
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://localhost:8443/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - walletnet

  db:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: on-failure
    tty: true
    volumes:
      - ./database:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - walletnet

volumes:
  database:
    driver: local