server:
  port: 8081

# MYSQL DATABASE
spring:
  datasource:
    url: jdbc:mysql://db:3307/wallet-consumer?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_ROOT_USER}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    url: http://localhost:8081/api-docs